name: Docker Build and Push  # Nom de l'action GitHub

on:  # Déclencheurs de l'action
  push:  # Sur les actions de push
    branches:  # Pour les branches spécifiques
      - master  # Branche master
  workflow_dispatch:  # Permet le déclenchement manuel

jobs:  # Définition des jobs
  build:  # Nom du job
    runs-on: ubuntu-latest  # Environnement sur lequel le job s'exécute

    steps:  # Étapes du job
      - name: Checkout code  # Nom de l'étape
        uses: actions/checkout@v2  # Action pour récupérer le code source

      - name: Set up Docker Buildx  # Nom de l'étape
        uses: docker/setup-buildx-action@v2  # Action pour configurer Docker Buildx

      - name: Login to Docker Hub  # Nom de l'étape
        uses: docker/login-action@v2  # Action pour se connecter à Docker Hub
        with:  # Paramètres de connexion
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Nom d'utilisateur Docker Hub stocké dans les secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Mot de passe Docker Hub stocké dans les secrets

      - name: Build and push Docker image  # Nom de l'étape
        uses: docker/build-push-action@v2  # Action pour construire et pousser l'image Docker
        with:  # Paramètres de construction et de push
          context: .  # Contexte de construction Docker (le répertoire courant)
          push: true  # Indique que l'image doit être poussée vers le registre Docker
          platforms: linux/arm64  # Plateforme cible pour l'image Docker, spécifiquement pour Raspberry Pi 4
          tags: |
            cedsanc/next-portfolio:latest
            cedsanc/next-portfolio:${{ github.run_number }}-${{ github.sha }}
          # Le premier tag est 'latest', le second utilise le numéro du run GitHub et le SHA du commit pour versionner l'image
